# Site settings
title: Python Agent DEvelopment framework
email: your-lucassmelo@dee.ufc.br
description: > # this means to ignore newlines until "baseurl:"
  PADE e um framework para desenvolvimento de sistemas multiagentes escrito em Python
  baseado na biblioteca Python Twisted e com base nos padroes FIPA
baseurl: "/Pade" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: lucas_LM
github_username:  lucassm

# Build settings
markdown: kramdown
